DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:98 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:115 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:115 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:115 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:115 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:90 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:104 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:115 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    urllib3.connectionpool:connectionpool.py:227 Starting new HTTP connection (1): 192.168.3.69:80
DEBUG    urllib3.connectionpool:connectionpool.py:452 http://192.168.3.69:80 "POST /dms/segment/statement/execute HTTP/1.1" 200 None